services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - drink_data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - COOKIE_SECURE=true # Comment if not using HTTPS

volumes:
  drink_data:
